[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test/unit"
evm_version = "cancun"
optimizer = true
optimizer-runs = 200
solc_version = "0.8.24"
auto_detect_remappings = false
max-line-length = 120
ffi = true

[profile.mainnet]
src = "src"
out = "out"
libs = ["lib"]
test = "test/mainnet"
eth_rpc_url = "bnb_mainnet"
evm_version = "cancun"
solc_version = "0.8.24"
auto_detect_remappings = false
max-line-length = 120
ffi = true
fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./" },
]

[profile.testnet]
src = "src"
out = "out"
libs = ["lib"]
test = "test/mainnet"
eth_rpc_url = "bnb_testnet"
evm_version = "cancun"
solc_version = "0.8.24"
max-line-length = 120
auto_detect_remappings = false
ffi = true
fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./" },
]


[rpc_endpoints]
bnb_mainnet = "https://bnb-mainnet.g.alchemy.com/v2/1FX7IZKqADVmU4ew3b7WD6NYNK5Ui0N7"
bnb_testnet = "https://rpc.ankr.com/bsc_testnet_chapel"

[fmt]
sort_imports = true
line_length = 120
wrap_comments = true

[etherscan]
bnb_mainnet = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api/" }
bnb_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api/" }
